---
title: "EPID 600: Module 2 Optional Reading"
output: html_document
---
***

#### Social Media Data

- [Project Well Being](http://wwbp.org/)

- [Using Twitter as a Data Source](http://blogs.lse.ac.uk/impactofsocialsciences/2015/07/10/social-media-research-tools-overview/)

#### Census and other GIS Data

- [Nathan Yau US Statistical Atlas - Amazing Plots, No Code](http://flowingdata.com/2015/06/16/reviving-the-statistical-atlas-of-the-united-states-with-new-data/)

- [Package for TIGER/Line Shapefiles](https://rpubs.com/walkerke/tigris)

- [2010 US Census Data in R](https://cran.r-project.org/web/packages/UScensus2010/index.html)

- [Analysis of Spatial Data in R](https://cran.r-project.org/web/views/Spatial.html)

#### Genetic Data

- [Genetics Timeline](https://unlockinglifescode.org/timeline)

- [1000 Genome Project End](http://www.wired.com/2015/09/power-1000-genomes/)

- [Whole Exome Sequencing Review](http://www.nature.com/jhg/journal/v59/n1/full/jhg2013114a.html)

- [Tutorials from the UK 100,000 Genomes Project](http://www.genomicsengland.co.uk/the-100000-genomes-project/understanding-genomics/)

- [Matt Might Talk on How to Face an Unknown Rare Disease and Challenging the "Not Actionable" Label](https://youtu.be/rx0kK6VnLSc)


#### Genomic Data

- [Classic gene expression study of breast cancer](http://www.nature.com/nature/journal/v415/n6871/full/415530a.html)

- [Batch effect example: rodents get stressed with male handlers and have decreased pain response](http://www.nature.com/news/male-researchers-stress-out-rodents-1.15106)

- [Batch effects overview](http://www.nature.com/nrg/journal/v11/n10/full/nrg2825.html)

- [Batch effects explained in straightforward terms](http://simplystatistics.org/2015/05/20/is-it-species-or-is-it-batch-they-are-confounded-so-we-cant-know/)

- [Batch effects discussion on twitter](http://www.nature.com/news/potential-flaws-in-genomics-paper-scrutinized-on-twitter-1.17591)

- [Reanalysis of paper where batch effects were not fully accounted for](http://f1000research.com/articles/4-121/v1)

- [What is a read mapping?](https://liorpachter.wordpress.com/2015/11/01/what-is-a-read-mapping/)

- [Unwanted effects when processing blood samples](http://www.pnas.org/content/111/47/16802.short)


#### Epigenetic Data

- [ENCODE](http://www.genome.gov/10005107)

- [ENCODE criticism as scientific viewpoint](http://www.pnas.org/content/110/14/5294)

- [ENCODE criticism overview](http://blogs.nature.com/news/2012/09/fighting-about-encode-and-junk.html)

- [Roadmap Epigenomics](http://www.roadmapepigenomics.org/)

#### Functional Annotation and Pathway Analysis

- [GSEA vs. DAVID](http://genomespot.blogspot.com.au/2016/02/pathway-analysis-david-versus-gsea.html)

- [On the dependence of enrichment results on reference pathways](http://biorxiv.org/content/early/2016/04/19/049288)

#### Cloud Computing

- [AWS Training](https://aws.amazon.com/training/intro_series/)

- [Angel Pizarro Podcast About AWS](http://mendelspod.com/podcasts/genomics-and-cloud-going-through-second-puberty-says-aws-angel-pizarro/)
